slug = "akaunting"
name = "Akaunting"
category = "App"
description = "From invoicing to expense tracking to accounting, Akaunting has all the tools you need to manage your money online, for free."
keywords = ["akaunting"]
compose = '''
services:
  akaunting:
    depends_on:
    - akaunting-db
    image: akaunting/akaunting:{{APP_VERSION}}
    restart: always
    environment:
      APP_URL: http://akaunting.{{ROOT_DOMAIN}}
      LOCALE: en-US
      AKAUNTING_SETUP: true
      DB_HOST: akaunting-db
      DB_PORT: 3306
      DB_USERNAME: akaunting
      DB_DATABASE: akaunting
      DB_NAME: akaunting
      DB_PASSWORD: '{{DB_PASS}}'
      DB_PREFIX: '{{DB_PREFIX}}'
      COMPANY_NAME: '{{COMPANY_NAME}}'
      COMPANY_EMAIL: '{{COMPANY_EMAIL}}'
      ADMIN_EMAIL: '{{ADMIN_EMAIL}}'
      ADMIN_PASSWORD: '{{ADMIN_PASSWORD}}'
    volumes:
    - akaunting-data:/akaunting-data
    - akaunting-modules:/akaunting-modules
  akaunting-db:
    image: mariadb:10.5.9
    volumes:
    - akaunting-db:/var/lib/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '{{DB_PASS}}'
      MYSQL_USER: akaunting
      MYSQL_PASSWORD: '{{DB_PASS}}'
      MYSQL_DATABASE: akaunting
    ports:
    - '{{HTTP_PORT}}:3306'
volumes:
  akaunting-data:
  akaunting-modules:
  akaunting-db:
'''

[[variables]]
key = "ADMIN_EMAIL"
label = "Admin Email"
default = "admin@company.com"
description = "This will be your default login username"

[[variables]]
key = "ADMIN_PASSWORD"
label = "Admin Password"
generate = true
description = "This will be your default login password"

[[variables]]
key = "APP_VERSION"
label = "Akaunting Version"
default = "3"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/akaunting/akaunting/tags"

[[variables]]
key = "COMPANY_EMAIL"
label = "Company Email"
description = "OPTIONAL"

[[variables]]
key = "COMPANY_NAME"
label = "Company Name"
description = "OPTIONAL"

[[variables]]
key = "DB_PASS"
label = "Database Password"
generate = true

[[variables]]
key = "DB_PREFIX"
label = "Database Prefix"
default = "aka_"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."
