slug = "archivebox"
name = "ArchiveBox"
category = "App"
description = "Open-source self-hosted web archiving."
keywords = ["archivebox"]
http_port = 8000
compose = '''
services:
  archivebox:
    image: archivebox/archivebox:{{ARCHIVEBOX_VERSION}}
    command: server --quick-init 0.0.0.0:8000
    volumes:
    - archivebox-data:/data
    environment:
      ALLOWED_HOSTS: '*'
      MEDIA_MAX_SIZE: '{{MAX_SIZE_IN_MO}}'
    ports:
    - '{{HTTP_PORT}}:8000'
volumes:
  archivebox-data:
'''

[[variables]]
key = "ARCHIVEBOX_VERSION"
label = "ArchiveBox version"
default = "stable"
description = "ArchiveBox image tag"

[[variables]]
key = "MAX_SIZE_IN_MO"
label = "Media max size"
default = "750m"
description = "Max size of media to download per archived page"
