slug = "calibre"
name = "Calibre Web"
category = "Database"
description = "Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database."
keywords = ["calibre", "web"]
http_port = 8083
compose = '''
services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:{{APP_VERSION}}
    environment:
      PUID: '{{PUID}}'
      PGID: '{{PGID}}'
      TZ: '{{TIMEZONE}}'
    volumes:
    - calibre-config:/config
    - calibre-books:/books
    ports:
    - '{{HTTP_PORT}}:8083'
volumes:
  calibre-config:
  calibre-books:
'''

[[variables]]
key = "APP_VERSION"
label = "Calibre-web version"
default = "0.6.26"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/linuxserver/calibre-web/tags"

[[variables]]
key = "PUID"
label = "User ID (PUID)"
default = "1000"
description = "UserID for the container process so file ownership matches the host."

[[variables]]
key = "PGID"
label = "Group ID (PGID)"
default = "1000"
description = "GroupID for the container process so file ownership matches the host."

[[variables]]
key = "TIMEZONE"
label = "Timezone"
default = "Europe/London"
description = "See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for list of timezones."
