slug = "chatwoot"
name = "Chatwoot"
category = "Communication"
description = "Open-source customer support SaaS alternative to Intercom, Drift, Crisp"
keywords = ["chatwoot"]
compose = '''
services:
  chatwoot-postgres:
    image: postgres:15
    volumes:
    - chatwoot-postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: chatwoot
      POSTGRES_PASSWORD: '{{CHATWOOT_POSTGRES_PASSWORD}}'
      POSTGRES_DB: chatwoot
  chatwoot-redis:
    volumes:
    - chatwoot-redis-data:/data
    restart: always
    environment:
      REDIS_PASSWORD: '{{CHATWOOT_REDIS_PASSWORD}}'
  chatwoot-web:
    restart: always
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'
      SECRET_KEY_BASE: '{{CHATWOOT_SECRET_KEY_BASE}}'
      POSTGRES_HOST: chatwoot-postgres
      POSTGRES_DATABASE: chatwoot
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: '{{CHATWOOT_POSTGRES_PASSWORD}}'
      REDIS_URL: redis://chatwoot-redis:6379
      REDIS_PASSWORD: '{{CHATWOOT_REDIS_PASSWORD}}'
      INSTALLATION_ENV: caprover
    ports:
    - '{{HTTP_PORT}}:3000'
  chatwoot-worker:
    restart: always
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'
      FRONTEND_URL: http://chatwoot.{{ROOT_DOMAIN}}
      SECRET_KEY_BASE: '{{CHATWOOT_SECRET_KEY_BASE}}'
      POSTGRES_HOST: chatwoot-postgres
      POSTGRES_DATABASE: chatwoot
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: '{{CHATWOOT_POSTGRES_PASSWORD}}'
      REDIS_URL: redis://chatwoot-redis:6379
      REDIS_PASSWORD: '{{CHATWOOT_REDIS_PASSWORD}}'
      INSTALLATION_ENV: caprover
volumes:
  chatwoot-postgres-data:
  chatwoot-redis-data:
'''

[[variables]]
key = "CHATWOOT_POSTGRES_PASSWORD"
label = "Postgres Password"
description = "Password must be at least 12 characters.  Please use a random string."

[[variables]]
key = "CHATWOOT_REDIS_PASSWORD"
label = "Redis Password"
description = "Password must be at least 12 characters. Please use a random string."

[[variables]]
key = "CHATWOOT_SECRET_KEY_BASE"
label = "Chatwoot Secret Key Base"
description = "The randomized string which is used to verify the integrity of signed cookies. Please use a string with more than 26 characters"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."
