slug = "clickhouse"
name = "ClickHouse"
category = "Database"
description = "Fast open-source column-oriented database management system for real-time analytics"
keywords = ["clickhouse"]
compose = '''
services:
  clickhouse:
    image: clickhouse/clickhouse-server:{{CLICKHOUSE_VERSION}}
    volumes:
    - clickhouse-data:/var/lib/clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: '{{CLICKHOUSE_DB}}'
      CLICKHOUSE_USER: '{{CLICKHOUSE_USER}}'
      CLICKHOUSE_PASSWORD: '{{CLICKHOUSE_PASSWORD}}'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '{{CLICKHOUSE_ACCESS_MANAGEMENT}}'
volumes:
  clickhouse-data:
'''

[[variables]]
key = "CLICKHOUSE_ACCESS_MANAGEMENT"
label = "Enable SQL-driven Access Control"
default = "1"
description = "Set to 1 to enable SQL-driven access control and account management (recommended)"

[[variables]]
key = "CLICKHOUSE_DB"
label = "Default Database"
default = "default"
description = "Initial database to create (optional, leave as 'default' if unsure)"

[[variables]]
key = "CLICKHOUSE_PASSWORD"
label = "Password"
generate = true
description = "Password for the user (auto-generated by default)"

[[variables]]
key = "CLICKHOUSE_USER"
label = "Username"
default = "clickhouse"
description = "Username for ClickHouse access (leave empty to use default user)"

[[variables]]
key = "CLICKHOUSE_VERSION"
label = "ClickHouse Version"
default = "24.11-alpine"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/clickhouse/clickhouse-server/tags"
