slug = "collabora-online"
name = "Collabora Online"
category = "App"
description = "Collabora Online is an online and collaborating office suite"
keywords = ["collabora", "online"]
compose = '''
services:
  collabora-online:
    image: collabora/code:{{COLLABORA_VERSION}}
    restart: always
    environment:
      domain: '{{WOPIHOST_DOMAIN}}'
      cert_domain: collabora-online.{{ROOT_DOMAIN}}
      server_name: collabora-online.{{ROOT_DOMAIN}}
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      username: '{{ADMIN_USER}}'
      password: '{{ADMIN_PASS}}'
    ports:
    - '{{HTTP_PORT}}:9980'
'''

[[variables]]
key = "ADMIN_PASS"
label = "Admin password"
generate = true
description = "Admin password - Please use a random string."

[[variables]]
key = "ADMIN_USER"
label = "Admin username"
default = "admin"
description = "Username for web admin interface"

[[variables]]
key = "COLLABORA_VERSION"
label = "Collabora CODE Version"
default = "25.04.2.1.1"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/collabora/code/tags/"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."

[[variables]]
key = "WOPIHOST_DOMAIN"
label = "WOPI host domain ( Optional )"
description = "Your WOPI host domain - yournextcloud.your.rootdomain.com Leave it empty if you don't use Nextcloud or ownCloud. Caution! You must add a backslash before each dot of the url"
