slug = "etherpad"
name = "Etherpad"
category = "App"
description = "Etherpad is a real-time collaborative editor for the web"
keywords = ["etherpad"]
http_port = 9001
compose = '''
services:
  etherpad:
    image: etherpad/etherpad:{{ETHERPAD_VERSION}}
    depends_on:
    - etherpad-db
    environment:
      NODE_ENV: production
      DB_TYPE: mysql
      DB_HOST: etherpad-db
      DB_PORT: '3306'
      DB_NAME: etherpad
      DB_USER: etherpad
      DB_PASS: '{{DB_PASS}}'
      DB_CHARSET: utf8mb4
      TRUST_PROXY: 'true'
    ports:
    - '{{HTTP_PORT}}:9001'
  etherpad-db:
    image: mysql:{{MYSQL_VERSION}}
    volumes:
    - etherpad-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '{{DB_PASS}}'
      MYSQL_DATABASE: etherpad
      MYSQL_USER: etherpad
      MYSQL_PASSWORD: '{{DB_PASS}}'
volumes:
  etherpad-db-data:
'''

[[variables]]
key = "DB_PASS"
label = "Database password"
generate = true
description = "Internal MySQL password Etherpad mints for itself."

[[variables]]
key = "ETHERPAD_VERSION"
label = "Etherpad Docker Image"
default = "2.6.1"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/etherpad/etherpad/tags"

[[variables]]
key = "MYSQL_VERSION"
label = "MySQL Version"
default = "8.4"
description = "Check out their Docker page for the valid tags https://hub.docker.com/_/mysql?tab=tags"
