slug = "fider"
name = "Fider - No Database"
category = "Database"
description = "Fider is a platform to collect and organize customer feedback."
keywords = ["database", "fider", "no"]
compose = '''
services:
  fider:
    documentation: Taken from https://hub.docker.com/r/getfider/fider/
    image: getfider/fider:{{FIDER_VERSION}}
    restart: always
    environment:
      BASE_URL: fider.{{ROOT_DOMAIN}}
      DATABASE_URL: '{{DB_URL}}'
      JWT_SECRET: '{{GEN_RANDOM_HEX}}(16)'
      EMAIL_NOREPLY: '{{EMAIL_NOREPLY}}'
      EMAIL_SMTP_HOST: '{{SMTP_HOST}}'
      EMAIL_SMTP_PORT: '{{SMTP_PORT}}'
      EMAIL_SMTP_USERNAME: '{{SMTP_USER}}'
      EMAIL_SMTP_PASSWORD: '{{SMTP_PASS}}'
    ports:
    - '{{HTTP_PORT}}:3000'
'''

[[variables]]
key = "DB_URL"
label = "Fider database URL"
description = "Postgres database connection URL for Fider, for example \"postgres://username:password@srv-captain--mypostgres:5432/fider?sslmode=disable\""

[[variables]]
key = "EMAIL_NOREPLY"
label = "SMTP sender email"
description = "The sender email address for your outgoing mail"

[[variables]]
key = "FIDER_VERSION"
label = "Fider Version"
default = "0.21.1"
description = "https://hub.docker.com/r/getfider/fider/tags"

[[variables]]
key = "GEN_RANDOM_HEX"
label = "Gen Random Hex"
default = ""

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."

[[variables]]
key = "SMTP_HOST"
label = "SMPT host"
description = "The host for your smtp server"

[[variables]]
key = "SMTP_PASS"
label = "SMTP password"
description = "The password for your smtp server"

[[variables]]
key = "SMTP_PORT"
label = "SMTP port"
description = "The port for your smtp server"

[[variables]]
key = "SMTP_USER"
label = "SMTP user"
description = "The user for your smtp server"
