slug = "focalboard"
name = "Focalboard"
category = "App"
description = "Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana."
keywords = ["focalboard"]
http_port = 8000
compose = '''
services:
  focalboard-db:
    image: postgres:{{POSTGRES_VERSION}}
    environment:
      POSTGRES_DB: '{{POSTGRES_DB}}'
      POSTGRES_USER: '{{POSTGRES_USER}}'
      POSTGRES_PASSWORD: '{{POSTGRES_PASSWORD}}'
    volumes:
    - focalboard-db-data:/var/lib/postgresql/data
  focalboard:
    image: mattermost/focalboard:{{FOCALBOARD_VERSION}}
    environment:
      CONFIG_JSON: '{"serverRoot":"http://focalboard:8000","port":8000,"dbtype":"postgres","dbconfig":"postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@focalboard-db/{{POSTGRES_DB}}?sslmode=disable&connect_timeout=10","postgres_dbconfig":"dbname={{POSTGRES_DB}} sslmode=disable","useSSL":false,"webpath":"./pack","filespath":"./files","telemetry":false,"session_expire_time":2592000,"session_refresh_time":18000,"localOnly":false,"enableLocalMode":true,"localModeSocketLocation":"/var/tmp/focalboard_local.socket"}'
    depends_on:
    - focalboard-db
    ports:
    - '{{HTTP_PORT}}:8000'
volumes:
  focalboard-db-data:
'''

[[variables]]
key = "FOCALBOARD_VERSION"
label = "Focalboard Version"
default = "7.11.4"
description = "mattermost/focalboard image tag. See https://hub.docker.com/r/mattermost/focalboard/tags"

[[variables]]
key = "POSTGRES_DB"
label = "Postgres Database"
default = "boards"

[[variables]]
key = "POSTGRES_PASSWORD"
label = "Postgres Password"
generate = true

[[variables]]
key = "POSTGRES_USER"
label = "Postgres User"
default = "boardsuser"

[[variables]]
key = "POSTGRES_VERSION"
label = "Postgres Version"
default = "16"
description = "Check out their docker page for the valid tags https://hub.docker.com/_/postgres?tab=tags"
