slug = "hasura"
name = "Hasura"
category = "Database"
description = "Instant realtime GraphQL APIs on any Postgres application, existing or new"
keywords = ["hasura"]
compose = '''
services:
  hasura-db:
    image: postgres:{{POSTGRES_VERSION}}
    volumes:
    - hasura-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: '{{PG_USER}}'
      POSTGRES_PASSWORD: '{{PG_PASS}}'
      POSTGRES_DB: '{{PG_DB}}'
      POSTGRES_INITDB_ARGS: '{{PG_INITDB_ARGS}}'
  hasura:
    image: hasura/graphql-engine:{{HASURA_VERSION}}
    depends_on:
    - hasura-db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://{{PG_USER}}:{{PG_PASS}}@hasura-db:5432/{{PG_DB}}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: '{{ADMIN_SECRET}}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    ports:
    - '{{HTTP_PORT}}:8080'
volumes:
  hasura-db-data:
'''

[[variables]]
key = "ADMIN_SECRET"
label = "Hasura admin secret(password)"
description = "The admin secret gives you access to the console."

[[variables]]
key = "HASURA_VERSION"
label = "Hasura Version"
default = "v1.2.2"
description = "Check out their GitHub page for their latest version https://github.com/hasura/graphql-engine"

[[variables]]
key = "PG_DB"
label = "Postgres Default Database"

[[variables]]
key = "PG_INITDB_ARGS"
label = "OPTIONAL: Arguments for 'postgres initdb'"
description = "For example, --data-checksums"

[[variables]]
key = "PG_PASS"
label = "Postgres Password"

[[variables]]
key = "PG_USER"
label = "Postgres Username"

[[variables]]
key = "POSTGRES_VERSION"
label = "Postgres Version"
default = "12"
