slug = "heimdall"
name = "Heimdall"
category = "App"
description = "Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way."
keywords = ["heimdall"]
http_port = 80
compose = '''
services:
  heimdall:
    image: linuxserver/heimdall:{{HEIMDALL_VERSION}}
    environment:
      TZ: '{{TZ}}'
    ports:
    - '{{HTTP_PORT}}:80'
    volumes:
    - heimdall-config:/config
volumes:
  heimdall-config:
'''

[[variables]]
key = "HEIMDALL_VERSION"
label = "Version Tag"
default = "version-2.2.2"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/linuxserver/heimdall/tags"

[[variables]]
key = "TZ"
label = "Timezone"
default = "Europe/Brussels"
description = "This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
