slug = "homarr"
name = "Homarr"
category = "App"
description = "Simple and lightweight homepage for your server, that helps you easily access all of your services in one place."
keywords = ["homarr"]
http_port = 7575
compose = '''
services:
  homarr:
    image: ghcr.io/ajnart/homarr:{{HOMARR_VERSION}}
    volumes:
    - homarr-configs:/app/data/configs
    - homarr-icons:/app/public/icons
    - homarr-data:/data
    environment:
      TZ: '{{HOMARR_TIMEZONE}}'
    ports:
    - '{{HTTP_PORT}}:7575'
volumes:
  homarr-configs:
  homarr-icons:
  homarr-data:
'''

[[variables]]
key = "HOMARR_TIMEZONE"
label = "Timezone"
default = "UTC"
description = "This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"

[[variables]]
key = "HOMARR_VERSION"
label = "Version Tag"
default = "0.15.10"
description = "Check out their GitHub packages page for the valid tags https://github.com/ajnart/homarr/pkgs/container/homarr"
