slug = "jitsi"
name = "Jitsi"
category = "Communication"
description = "Free open-source video conferencing for web & mobile"
keywords = ["jitsi"]
compose = '''
services:
  jitsi-web:
    image: jitsi/web:{{TAG_VERSION}}
    restart: unless-stopped
    ports:
    - '{{HTTPS_PORT}}:443'
    - '{{HTTP_PORT}}:80'
    volumes:
    - jitsi-web:/config
    - jitsi-web-transcripts:/usr/share/jitsi-meet/transcripts
    environment:
      JICOFO_COMPONENT_SECRET: '{{PASSWORD}}'
      JICOFO_AUTH_PASSWORD: '{{PASSWORD}}'
      JVB_AUTH_PASSWORD: '{{PASSWORD}}'
      JIGASI_XMPP_PASSWORD: '{{PASSWORD}}'
      JIBRI_RECORDER_PASSWORD: '{{PASSWORD}}'
      JIBRI_XMPP_PASSWORD: '{{PASSWORD}}'
      HTTP_PORT: '{{HTTP_PORT}}'
      HTTPS_PORT: '{{HTTPS_PORT}}'
      TZ: '{{TIMEZONE}}'
      XMPP_DOMAIN: meet.jitsi
      XMPP_SERVER: jitsi-prosody
      XMPP_BOSH_URL_BASE: http://jitsi-prosody:5280
      XMPP_AUTH_DOMAIN: auth.meet.jitsi
      XMPP_MUC_DOMAIN: muc.meet.jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
      XMPP_GUEST_DOMAIN: guest.meet.jitsi
      XMPP_MODULES: ''
      XMPP_MUC_MODULES: ''
      XMPP_INTERNAL_MUC_MODULES: ''
      JVB_BREWERY_MUC: jvbbrewery
      JVB_AUTH_USER: jvb
      JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
      JVB_PORT: '{{JVB_UDP}}'
      JVB_TCP_HARVESTER_DISABLED: 'true'
      JVB_TCP_PORT: '{{JVB_TCP}}'
      JICOFO_AUTH_USER: focus
      JIGASI_XMPP_USER: jigasi
      JIGASI_BREWERY_MUC: jigasibrewery
      JIGASI_PORT_MIN: '20000'
      JIGASI_PORT_MAX: '20050'
      XMPP_RECORDER_DOMAIN: recorder.meet.jitsi
      JIBRI_RECORDER_USER: recorder
      JIBRI_RECORDING_DIR: /config/recordings
      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
      JIBRI_XMPP_USER: jibri
      JIBRI_BREWERY_MUC: jibribrewery
      JIBRI_PENDING_TIMEOUT: '90'
      JIBRI_STRIP_DOMAIN_JID: muc
      JIBRI_LOGS_DIR: /config/logs
  jitsi-prosody:
    image: jitsi/prosody:{{TAG_VERSION}}
    restart: unless-stopped
    expose:
    - '5222'
    - '5347'
    - '5280'
    volumes:
    - jitsi-prosody:/config
    environment:
      JICOFO_COMPONENT_SECRET: '{{PASSWORD}}'
      JICOFO_AUTH_PASSWORD: '{{PASSWORD}}'
      JVB_AUTH_PASSWORD: '{{PASSWORD}}'
      JIGASI_XMPP_PASSWORD: '{{PASSWORD}}'
      JIBRI_RECORDER_PASSWORD: '{{PASSWORD}}'
      JIBRI_XMPP_PASSWORD: '{{PASSWORD}}'
      HTTP_PORT: '{{HTTP_PORT}}'
      HTTPS_PORT: '{{HTTPS_PORT}}'
      TZ: '{{TIMEZONE}}'
      XMPP_DOMAIN: meet.jitsi
      XMPP_SERVER: jitsi-prosody
      XMPP_BOSH_URL_BASE: http://jitsi-prosody:5280
      XMPP_AUTH_DOMAIN: auth.meet.jitsi
      XMPP_MUC_DOMAIN: muc.meet.jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
      XMPP_GUEST_DOMAIN: guest.meet.jitsi
      XMPP_MODULES: ''
      XMPP_MUC_MODULES: ''
      XMPP_INTERNAL_MUC_MODULES: ''
      JVB_BREWERY_MUC: jvbbrewery
      JVB_AUTH_USER: jvb
      JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
      JVB_PORT: '{{JVB_UDP}}'
      JVB_TCP_HARVESTER_DISABLED: 'true'
      JVB_TCP_PORT: '{{JVB_TCP}}'
      JICOFO_AUTH_USER: focus
      JIGASI_XMPP_USER: jigasi
      JIGASI_BREWERY_MUC: jigasibrewery
      JIGASI_PORT_MIN: '20000'
      JIGASI_PORT_MAX: '20050'
      XMPP_RECORDER_DOMAIN: recorder.meet.jitsi
      JIBRI_RECORDER_USER: recorder
      JIBRI_RECORDING_DIR: /config/recordings
      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
      JIBRI_XMPP_USER: jibri
      JIBRI_BREWERY_MUC: jibribrewery
      JIBRI_PENDING_TIMEOUT: '90'
      JIBRI_STRIP_DOMAIN_JID: muc
      JIBRI_LOGS_DIR: /config/logs
  jitsi-jicofo:
    image: jitsi/jicofo:{{TAG_VERSION}}
    restart: unless-stopped
    volumes:
    - jitsi-jicofo:/config
    environment:
      JICOFO_COMPONENT_SECRET: '{{PASSWORD}}'
      JICOFO_AUTH_PASSWORD: '{{PASSWORD}}'
      JVB_AUTH_PASSWORD: '{{PASSWORD}}'
      JIGASI_XMPP_PASSWORD: '{{PASSWORD}}'
      JIBRI_RECORDER_PASSWORD: '{{PASSWORD}}'
      JIBRI_XMPP_PASSWORD: '{{PASSWORD}}'
      HTTP_PORT: '{{HTTP_PORT}}'
      HTTPS_PORT: '{{HTTPS_PORT}}'
      TZ: '{{TIMEZONE}}'
      XMPP_DOMAIN: meet.jitsi
      XMPP_SERVER: jitsi-prosody
      XMPP_BOSH_URL_BASE: http://jitsi-prosody:5280
      XMPP_AUTH_DOMAIN: auth.meet.jitsi
      XMPP_MUC_DOMAIN: muc.meet.jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
      XMPP_GUEST_DOMAIN: guest.meet.jitsi
      XMPP_MODULES: ''
      XMPP_MUC_MODULES: ''
      XMPP_INTERNAL_MUC_MODULES: ''
      JVB_BREWERY_MUC: jvbbrewery
      JVB_AUTH_USER: jvb
      JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
      JVB_PORT: '{{JVB_UDP}}'
      JVB_TCP_HARVESTER_DISABLED: 'true'
      JVB_TCP_PORT: '{{JVB_TCP}}'
      JICOFO_AUTH_USER: focus
      JIGASI_XMPP_USER: jigasi
      JIGASI_BREWERY_MUC: jigasibrewery
      JIGASI_PORT_MIN: '20000'
      JIGASI_PORT_MAX: '20050'
      XMPP_RECORDER_DOMAIN: recorder.meet.jitsi
      JIBRI_RECORDER_USER: recorder
      JIBRI_RECORDING_DIR: /config/recordings
      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
      JIBRI_XMPP_USER: jibri
      JIBRI_BREWERY_MUC: jibribrewery
      JIBRI_PENDING_TIMEOUT: '90'
      JIBRI_STRIP_DOMAIN_JID: muc
      JIBRI_LOGS_DIR: /config/logs
    depends_on:
    - jitsi-prosody
  jitsi-jvb:
    image: jitsi/jvb:{{TAG_VERSION}}
    restart: unless-stopped
    ports:
    - '{{JVB_UDP}}:{{JVB_UDP}}'
    - '{{JVB_TCP}}:{{JVB_TCP}}'
    volumes:
    - jitsi-jvb:/config
    environment:
      JICOFO_COMPONENT_SECRET: '{{PASSWORD}}'
      JICOFO_AUTH_PASSWORD: '{{PASSWORD}}'
      JVB_AUTH_PASSWORD: '{{PASSWORD}}'
      JIGASI_XMPP_PASSWORD: '{{PASSWORD}}'
      JIBRI_RECORDER_PASSWORD: '{{PASSWORD}}'
      JIBRI_XMPP_PASSWORD: '{{PASSWORD}}'
      HTTP_PORT: '{{HTTP_PORT}}'
      HTTPS_PORT: '{{HTTPS_PORT}}'
      TZ: '{{TIMEZONE}}'
      XMPP_DOMAIN: meet.jitsi
      XMPP_SERVER: jitsi-prosody
      XMPP_BOSH_URL_BASE: http://jitsi-prosody:5280
      XMPP_AUTH_DOMAIN: auth.meet.jitsi
      XMPP_MUC_DOMAIN: muc.meet.jitsi
      XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
      XMPP_GUEST_DOMAIN: guest.meet.jitsi
      XMPP_MODULES: ''
      XMPP_MUC_MODULES: ''
      XMPP_INTERNAL_MUC_MODULES: ''
      JVB_BREWERY_MUC: jvbbrewery
      JVB_AUTH_USER: jvb
      JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
      JVB_PORT: '{{JVB_UDP}}'
      JVB_TCP_HARVESTER_DISABLED: 'true'
      JVB_TCP_PORT: '{{JVB_TCP}}'
      JICOFO_AUTH_USER: focus
      JIGASI_XMPP_USER: jigasi
      JIGASI_BREWERY_MUC: jigasibrewery
      JIGASI_PORT_MIN: '20000'
      JIGASI_PORT_MAX: '20050'
      XMPP_RECORDER_DOMAIN: recorder.meet.jitsi
      JIBRI_RECORDER_USER: recorder
      JIBRI_RECORDING_DIR: /config/recordings
      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
      JIBRI_XMPP_USER: jibri
      JIBRI_BREWERY_MUC: jibribrewery
      JIBRI_PENDING_TIMEOUT: '90'
      JIBRI_STRIP_DOMAIN_JID: muc
      JIBRI_LOGS_DIR: /config/logs
    depends_on:
    - jitsi-prosody
volumes:
  jitsi-web:
  jitsi-web-transcripts:
  jitsi-prosody:
  jitsi-jicofo:
  jitsi-jvb:
'''

[[variables]]
key = "HTTPS_PORT"
label = "HTTPS Port"
default = "8443"
description = "This is the HTTPS port to access Jitsi"

[[variables]]
key = "JVB_TCP"
label = "JVB TCP Port"
default = "4443"
description = "TCP Port for JVB service"

[[variables]]
key = "JVB_UDP"
label = "JVB UDP Port"
default = "10000"
description = "UDP Port for JVB service"

[[variables]]
key = "PASSWORD"
label = "Password"
default = "pass"
description = "This is the password for Jitsi's services"

[[variables]]
key = "TAG_VERSION"
label = "Docker tag version"
default = "4416"
description = "You can check the version in Docker Hub: https://hub.docker.com/r/jitsi/web/tags"

[[variables]]
key = "TIMEZONE"
label = "Timezone"
default = "Europe/Amsterdam"
description = "This is the timezone for Jitsi"
