slug = "jsreport"
name = "jsreport"
category = "App"
description = "jsreport is an open source reporting platform where reports are designed using popular JavaScript templating engines"
keywords = ["jsreport"]
compose = '''
services:
  jsreport:
    image: jsreport/jsreport:{{JSREPORT_VERSION}}
    volumes:
    - jsreport-data:/jsreport
    restart: always
    environment:
      extensions_authentication_admin_username: '{{JSREPORT_ADMINUSERNAME}}'
      extensions_authentication_admin_password: '{{JSREPORT_PASSWORD}}'
      extensions_authentication_cookieSession_secret: '{{JSREPORT_SECRET}}'
    ports:
    - '{{HTTP_PORT}}:5488'
volumes:
  jsreport-data:
'''

[[variables]]
key = "JSREPORT_ADMINUSERNAME"
label = "Admin user name"
default = "admin"
description = "Only use alphanumeric chars."

[[variables]]
key = "JSREPORT_PASSWORD"
label = "Admin password"

[[variables]]
key = "JSREPORT_SECRET"
label = "Session secret"
default = "long-secret"

[[variables]]
key = "JSREPORT_VERSION"
label = "version"
default = "2.4.0-full"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/jsreport/jsreport/tags"
