slug = "kanboard-sqlite"
name = "Kanboard SQLite"
category = "Database"
description = "Kanboard is a free and open source Kanban project management software."
keywords = ["kanboard", "sqlite"]
compose = '''
services:
  kanboard-sqlite:
    image: kanboard/kanboard:{{VERSION}}
    environment:
      PLUGIN_INSTALLER: '{{PLUGIN_INSTALLER}}'
    volumes:
    - kanboard-sqlite-data:/var/www/app/data
    - kanboard-sqlite-plugins:/var/www/app/plugins
    - kanboard-sqlite-ssl:/etc/nginx/ssl
volumes:
  kanboard-sqlite-data:
  kanboard-sqlite-plugins:
  kanboard-sqlite-ssl:
'''

[[variables]]
key = "PLUGIN_INSTALLER"
label = "Plugin installer"
default = "true"
description = "Allow plugin installer"

[[variables]]
key = "VERSION"
label = "Kanboard Version"
default = "v1.2.15"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/kanboard/kanboard/tags"
