slug = "keila"
name = "Keila"
category = "Communication"
description = "Free and open source email newsletter tool."
keywords = ["keila"]
compose = '''
services:
  keila:
    image: pentacent/keila:{{KEILA_VERSION}}
    environment:
      DB_URL: postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@keila-db/{{POSTGRES_DATABASE}}
      DB_ENABLE_SSL: '{{KEILA_DB_ENABLE_SSL}}'
      KEILA_USER: '{{KEILA_USER}}'
      KEILA_PASSWORD: '{{KEILA_PASSWORD}}'
      URL_HOST: keila.{{ROOT_DOMAIN}}
      URL_PATH: '{{KEILA_URL_PATH}}'
      URL_SCHEMA: '{{KEILA_URL_SCHEMA}}'
      URL_PORT: '{{KEILA_URL_PORT}}'
      PORT: '{{KEILA_PORT}}'
      SECRET_KEY_BASE: '{{KEILA_SECRET_KEY_BASE}}'
      DISABLE_REGISTRATION: '{{KEILA_DISABLE_REGISTRATION}}'
      DISABLE_PRECEDENCE_HEADER: '{{KEILA_DISABLE_PRECEDENCE_HEADER}}'
      MAILER_TYPE: '{{KEILA_MAILER_TYPE}}'
      MAILER_SMTP_HOST: '{{KEILA_MAILER_SMTP_HOST}}'
      MAILER_SMTP_PORT: '{{KEILA_MAILER_SMTP_PORT}}'
      MAILER_SMTP_USER: '{{KEILA_MAILER_SMTP_USER}}'
      MAILER_SMTP_PASSWORD: '{{KEILA_MAILER_SMTP_PASSWORD}}'
      CAPTCHA_PROVIDER: '{{KEILA_CAPTCHA_PROVIDER}}'
      CAPTCHA_SITE_KEY: '{{KEILA_CAPTCHA_SITE_KEY}}'
      CAPTCHA_SECRET_KEY: '{{KEILA_CAPTCHA_SECRET_KEY}}'
      CAPTCHA_URL: '{{KEILA_CAPTCHA_URL}}'
    depends_on:
    - keila-db
    volumes:
    - keila-upload:/opt/app/uploads
    ports:
    - '{{HTTP_PORT}}:$$cap_KEILA_PORT'
  keila-db:
    image: postgres:{{POSTGRES_VERSION}}
    environment:
      POSTGRES_USER: '{{POSTGRES_USER}}'
      POSTGRES_PASSWORD: '{{POSTGRES_PASSWORD}}'
      POSTGRES_DB: '{{POSTGRES_DATABASE}}'
    volumes:
    - keila-db:/var/lib/postgresql/data
volumes:
  keila-upload:
  keila-db:
'''

[[variables]]
key = "KEILA_CAPTCHA_PROVIDER"
label = "Keila | Captcha Provider"
default = "hcaptcha"
description = "Provider that serves the Captcha."

[[variables]]
key = "KEILA_CAPTCHA_SECRET_KEY"
label = "Keila | Captcha Secret Key"
description = "Secret key for captcha provider."

[[variables]]
key = "KEILA_CAPTCHA_SITE_KEY"
label = "Keila | Captcha Site Key"
description = "Site key for captcha provider."

[[variables]]
key = "KEILA_CAPTCHA_URL"
label = "Keila | Captcha Verification URL"
description = "Verification URL for captcha provider."

[[variables]]
key = "KEILA_DB_ENABLE_SSL"
label = "Keila | Database SSL"
default = "false"
description = "Whether to use SSL for database connection."

[[variables]]
key = "KEILA_DISABLE_PRECEDENCE_HEADER"
label = "Keila | Disable Precedence Header"
default = "false"
description = "Disable the `Precedence: Bulk` header by setting this variable to `true`."

[[variables]]
key = "KEILA_DISABLE_REGISTRATION"
label = "Keila | Disable Registration"
default = "true"
description = "Disable user registration by setting this variable to `true`."

[[variables]]
key = "KEILA_MAILER_SMTP_HOST"
label = "Keila | SMTP Server Hostname"
description = "Hostname of the SMTP server."

[[variables]]
key = "KEILA_MAILER_SMTP_PASSWORD"
label = "Keila | SMTP Password"
description = "Password for the SMTP server."

[[variables]]
key = "KEILA_MAILER_SMTP_PORT"
label = "Keila | SMTP Server Port"
default = "587"
description = "Port of the SMTP server."

[[variables]]
key = "KEILA_MAILER_SMTP_USER"
label = "Keila | SMTP User"
description = "Username for the SMTP server."

[[variables]]
key = "KEILA_MAILER_TYPE"
label = "Keila | Mailer Type"
default = "smtp"
description = "Mail delivery type. Currently only `smtp` is supported."

[[variables]]
key = "KEILA_PASSWORD"
label = "Keila | Administrator Password"
generate = true
description = "Password for the root user."

[[variables]]
key = "KEILA_PORT"
label = "Keila | Port"
default = "4000"
description = "Port of Keila host."

[[variables]]
key = "KEILA_SECRET_KEY_BASE"
label = "Keila | Secret Key Base"
generate = true
description = "Strong secret with at least 64 characters. Can be generated with `head -c 48 /dev/urandom`"

[[variables]]
key = "KEILA_URL_PATH"
label = "Keila | URL Path"
default = "/"
description = "Path of your Keila instance."

[[variables]]
key = "KEILA_URL_PORT"
label = "Keila | URL Port"
default = "80"
description = "Port of your Keila instance. Use `80` for schema `http` or `443` for schema `https`."

[[variables]]
key = "KEILA_URL_SCHEMA"
label = "Keila | URL Schema"
default = "http"
description = "Use `http` or `https`. URL scheme of your Keila instance."

[[variables]]
key = "KEILA_USER"
label = "Keila | Administrator User"
description = "Email address for the root user."

[[variables]]
key = "KEILA_VERSION"
label = "Keila | Version Tag"
default = "0.12.2"
description = "Check out their valid tags at https://hub.docker.com/r/pentacent/keila/tags"

[[variables]]
key = "POSTGRES_DATABASE"
label = "PostgreSQL | Database"
default = "keila"
description = "Database name."

[[variables]]
key = "POSTGRES_PASSWORD"
label = "PostgreSQL | Password"
generate = true
description = "Database user password."

[[variables]]
key = "POSTGRES_USER"
label = "PostgreSQL | User"
default = "keila"
description = "Database user."

[[variables]]
key = "POSTGRES_VERSION"
label = "PostgreSQL | Version Tag"
default = "14.5"
description = "Check out their valid tags at https://hub.docker.com/_/postgres/tags"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."
