slug = "kimai2"
name = "Kimai"
category = "App"
description = "With Kimai, the boring process of feeding spreadsheets with your working hours is not only simplified, it also offers dozens of other exciting features that you don't even know you're missing!"
keywords = ["kimai", "kimai2"]
compose = '''
services:
  kimai2-fpm:
    depends_on:
    - kimai2-db
    image: kimai/kimai2:{{KIMAI_VERSION}}
    restart: always
    environment:
      ADMINMAIL: '{{KIMAI}}-adminmail'
      ADMINPASS: '{{KIMAI}}-adminpass'
      MAILER_URL: '{{KIMAI}}-mailerurl'
      MAILER_FROM: '{{KIMAI}}-mailerfrom'
      DATABASE_URL: mysql://{{MARIADB}}-user:{{MARIADB}}-pass@kimai2-db/{{MARIADB}}-db
      TRUSTED_HOSTS: kimai2.{{ROOT_DOMAIN}},nginx,localhost,127.0.0.1
    volumes:
    - kimai2-public:/opt/kimai/public
  kimai2-db:
    image: mariadb:{{MARIADB_VERSION}}
    environment:
      MYSQL_DATABASE: '{{MARIADB}}-db'
      MYSQL_USER: '{{MARIADB}}-user'
      MYSQL_PASSWORD: '{{MARIADB}}-pass'
      MYSQL_ROOT_PASSWORD: '{{MARIADB}}-rootpass'
    volumes:
    - kimai2-db-data:/var/lib/mysql
    restart: unless-stopped
    ports:
    - '{{HTTP_PORT}}:3306'
  kimai2:
    image: lcxat/nginx-fpm-reverse-proxy:{{NGINX_VERSION}}
    environment:
      FPM_NGINX_HOST: kimai2-fpm
    volumes:
    - kimai2-public:/opt/kimai/public:ro
    depends_on:
    - kimai2-fpm
    restart: unless-stopped
volumes:
  kimai2-public:
  kimai2-db-data:
'''

[[variables]]
key = "KIMAI"
label = "Kimai"
default = ""

[[variables]]
key = "KIMAI_VERSION"
label = "Version Tag"
default = "fpm-1.15.2-prod"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/kimai/kimai2/tags"

[[variables]]
key = "MARIADB"
label = "Mariadb"
default = ""

[[variables]]
key = "MARIADB_VERSION"
label = "mariaDB Version"
default = "10"
description = "Check out their docker page for the valid tags https://hub.docker.com/_/mariadb"

[[variables]]
key = "NGINX_VERSION"
label = "nginx fpm Version"
default = "1.21.3"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/lcxat/nginx-fpm-reverse-proxy/tags"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."
