slug = "lago"
name = "Lago"
category = "App"
description = "Open source billing API for product-led SaaS"
keywords = ["lago"]
compose = '''
services:
  lago:
    image: getlago/front:{{LAGO_VERSION}}
    hostname: lago.{{ROOT_DOMAIN}}
    environment:
      API_URL: http://lago-api.{{ROOT_DOMAIN}}
      APP_ENV: '{{LAGO_ENVIRONMENT}}'
      CODEGEN_API: http://lago-api.{{ROOT_DOMAIN}}
      LAGO_DISABLE_SIGNUP: '{{LAGO_DISABLE_SIGNUP}}'
    depends_on:
    - lago-api
  lago-api:
    hostname: lago-api.{{ROOT_DOMAIN}}
    environment:
      LAGO_API_URL: http://lago-api.{{ROOT_DOMAIN}}
      DATABASE_URL: postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@lago-db/{{POSTGRES_DB}}
      REDIS_URL: redis://lago-cache
      SECRET_KEY_BASE: '{{LAGO_API_SECRET_KEY_BASE}}'
      RAILS_ENV: '{{LAGO_ENVIRONMENT}}'
      RAILS_LOG_TO_STDOUT: '{{LAGO_API_LOG_TO_STDOUT}}'
      SENTRY_DSN: '{{LAGO_API_SENTRY_DSN}}'
      LAGO_FRONT_URL: http://lago.{{ROOT_DOMAIN}}
      RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      LAGO_RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      LAGO_SIDEKIQ_WEB: '{{LAGO_API_SIDEKIQ_WEB}}'
      ENCRYPTION_PRIMARY_KEY: '{{LAGO_API_ENCRYPTION_PRIMARY_KEY}}'
      ENCRYPTION_DETERMINISTIC_KEY: '{{LAGO_API_ENCRYPTION_DETERMINISTIC_KEY}}'
      ENCRYPTION_KEY_DERIVATION_SALT: '{{LAGO_API_ENCRYPTION_KEY_DERIVATION_SALT}}'
      LAGO_USE_AWS_S3: '{{LAGO_API_USE_AWS_S3}}'
      LAGO_AWS_S3_ACCESS_KEY_ID: '{{LAGO_API_AWS_S3_ACCESS_KEY_ID}}'
      LAGO_AWS_S3_SECRET_ACCESS_KEY: '{{LAGO_API_AWS_S3_SECRET_ACCESS_KEY}}'
      LAGO_AWS_S3_REGION: '{{LAGO_API_AWS_S3_REGION}}'
      LAGO_AWS_S3_BUCKET: '{{LAGO_API_AWS_S3_BUCKET}}'
      LAGO_AWS_S3_ENDPOINT: '{{LAGO_API_AWS_S3_ENDPOINT}}'
      LAGO_PDF_URL: http://lago-pdf
      LAGO_REDIS_CACHE_URL: redis://lago-cache
      LAGO_DISABLE_SEGMENT: '{{LAGO_API_DISABLE_SEGMENT}}'
    volumes:
    - lago-api-storage-data:/app/storage
    depends_on:
    - lago-db
    - lago-cache
    ports:
    - '{{HTTP_PORT}}:$$cap_LAGO_API_PORT'
  lago-api-worker:
    environment:
      LAGO_API_URL: http://lago-api.{{ROOT_DOMAIN}}
      DATABASE_URL: postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@lago-db/{{POSTGRES_DB}}
      REDIS_URL: redis://lago-cache
      SECRET_KEY_BASE: '{{LAGO_API_SECRET_KEY_BASE}}'
      RAILS_ENV: '{{LAGO_ENVIRONMENT}}'
      RAILS_LOG_TO_STDOUT: '{{LAGO_API_LOG_TO_STDOUT}}'
      SENTRY_DSN: '{{LAGO_API_SENTRY_DSN}}'
      LAGO_RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      ENCRYPTION_PRIMARY_KEY: '{{LAGO_API_ENCRYPTION_PRIMARY_KEY}}'
      ENCRYPTION_DETERMINISTIC_KEY: '{{LAGO_API_ENCRYPTION_DETERMINISTIC_KEY}}'
      ENCRYPTION_KEY_DERIVATION_SALT: '{{LAGO_API_ENCRYPTION_KEY_DERIVATION_SALT}}'
      LAGO_USE_AWS_S3: '{{LAGO_API_USE_AWS_S3}}'
      LAGO_AWS_S3_ACCESS_KEY_ID: '{{LAGO_API_AWS_S3_ACCESS_KEY_ID}}'
      LAGO_AWS_S3_SECRET_ACCESS_KEY: '{{LAGO_API_AWS_S3_SECRET_ACCESS_KEY}}'
      LAGO_AWS_S3_REGION: '{{LAGO_API_AWS_S3_REGION}}'
      LAGO_AWS_S3_BUCKET: '{{LAGO_API_AWS_S3_BUCKET}}'
      LAGO_AWS_S3_ENDPOINT: '{{LAGO_API_AWS_S3_ENDPOINT}}'
      LAGO_PDF_URL: http://lago-pdf
      LAGO_REDIS_CACHE_URL: redis://lago-cache
      LAGO_DISABLE_SEGMENT: '{{LAGO_API_DISABLE_SEGMENT}}'
    volumes:
    - lago-api-storage-data:/app/storage
    depends_on:
    - lago-api
  lago-api-clock:
    environment:
      LAGO_API_URL: http://lago-api.{{ROOT_DOMAIN}}
      DATABASE_URL: postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@lago-db/{{POSTGRES_DB}}
      REDIS_URL: redis://lago-cache
      SECRET_KEY_BASE: '{{LAGO_API_SECRET_KEY_BASE}}'
      RAILS_ENV: '{{LAGO_ENVIRONMENT}}'
      RAILS_LOG_TO_STDOUT: '{{LAGO_API_LOG_TO_STDOUT}}'
      SENTRY_DSN: '{{LAGO_API_SENTRY_DSN}}'
      LAGO_RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      RSA_PRIVATE_KEY: '{{LAGO_API_RSA_PRIVATE_KEY}}'
      ENCRYPTION_PRIMARY_KEY: '{{LAGO_API_ENCRYPTION_PRIMARY_KEY}}'
      ENCRYPTION_DETERMINISTIC_KEY: '{{LAGO_API_ENCRYPTION_DETERMINISTIC_KEY}}'
      ENCRYPTION_KEY_DERIVATION_SALT: '{{LAGO_API_ENCRYPTION_KEY_DERIVATION_SALT}}'
    depends_on:
    - lago-api
  lago-pdf:
    image: getlago/lago-gotenberg:{{GOTENBERG_VERSION}}
  lago-db:
    image: postgres:{{POSTGRES_VERSION}}
    environment:
      POSTGRES_DB: '{{POSTGRES_DB}}'
      POSTGRES_USER: '{{POSTGRES_USER}}'
      POSTGRES_PASSWORD: '{{POSTGRES_PASSWORD}}'
      PGDATA: '{{POSTGRES_PGDATA}}'
    volumes:
    - lago-db-data:/data/postgres
  lago-cache:
    image: redis:{{REDIS_VERSION}}
    volumes:
    - lago-cache-data:/data
volumes:
  lago-api-storage-data:
  lago-db-data:
  lago-cache-data:
'''

[[variables]]
key = "GOTENBERG_VERSION"
label = "General | Gotenberg Version"
default = "7"
description = "Check out their valid tags at https://hub.docker.com/r/getlago/lago-gotenberg/tags"

[[variables]]
key = "LAGO_API_AWS_S3_ACCESS_KEY_ID"
label = "API | AWS S3 Access Key ID"
description = "AWS access key ID that has access to S3."

[[variables]]
key = "LAGO_API_AWS_S3_BUCKET"
label = "API | AWS S3 Bucket"
description = "AWS S3 bucket name."

[[variables]]
key = "LAGO_API_AWS_S3_ENDPOINT"
label = "API | AWS S3 Endpoint"
description = "S3 compatible storage endpoint. Should be set only if you are using another storage provider than AWS S3."

[[variables]]
key = "LAGO_API_AWS_S3_REGION"
label = "API | AWS S3 Region"
description = "AWS S3 region (e.g. `us-east-1`)."

[[variables]]
key = "LAGO_API_AWS_S3_SECRET_ACCESS_KEY"
label = "API | AWS S3 Secret Access Key"
description = "AWS secret access key that has access to S3."

[[variables]]
key = "LAGO_API_DISABLE_SEGMENT"
label = "API | Disable Tracking"
default = "true"
description = "Whether to opt-out of analytics."

[[variables]]
key = "LAGO_API_ENCRYPTION_DETERMINISTIC_KEY"
label = "API | Encryption Deterministic Key"
generate = true
description = "Encryption deterministic key used to secure sensitive values stored in the database. You should generate one using this command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`."

[[variables]]
key = "LAGO_API_ENCRYPTION_KEY_DERIVATION_SALT"
label = "API | Encryption Key Derivation Salt"
generate = true
description = "Encryption key salt used to secure sensitive values stored in the database. You should generate one using this command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`."

[[variables]]
key = "LAGO_API_ENCRYPTION_PRIMARY_KEY"
label = "API | Encryption Primary Key"
generate = true
description = "Encryption primary key used to secure sensitive values stored in the database. You should generate one using this command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`."

[[variables]]
key = "LAGO_API_LOG_TO_STDOUT"
label = "API | Output Log"
default = "true"
description = "Whether to log output to `stdout`. Should be left untouched."

[[variables]]
key = "LAGO_API_RSA_PRIVATE_KEY"
label = "API | RSA Private Key"
default = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMmVmN0Eyc216b25PRU9oRm5wZ2gwZEd4Zk1JUXR1M290YlREcFFKdkxUTzl0YUhRCnlIZDRwUU5KNytqdW5EMy82QXZCbk1tQ0p4a3JJcDNrZ0xUN0tFTTFKaGVVdU90TXlvUWVSYTFYVEVUR2RiN24KWHN6WnBGRVBsYXFHUVVMeWZGTUVUTXh6elJPK0JOZFg3SFRkeDEwTi8vTklJTHBoSlJORm1QRlhDTXJodTFTbQpMVjQ2UmVkUm9JZjI1Z05XY0FHeG9STkZXcEJtUENienJZM2VTUDJpUFYwOHZwUDZ2aWFBSWpWd2VoSEhXTU05CmNzQitlYXJGRk9aRllROE9hOFVBS1RFVUNSVWhyelorS2ZmVkNRVjlrOW4rV0tueks2MlUvVXlveWZZV2hiZXIKeWJYdmliSlE2eXcxdElYZFJrL1lseVFEVmxFK080Qlk1WWV1cHdJREFRQUJBb0lCQUhIZlVNV1FrVThOcEtvaApONENSYjlyK0FncDRQOVBZcit1RTgxaWYxUW1DS0hscWZuakVOai9GWURZSE8rcGFYQWtmVzZaYmg3QjI3cHZBCmQxRHJRdlRmYWo3bHc4cCs3RHBJb0trNDFJMyt3dGQxVStPdW1XM05EcC9mNVJqbHEySmMzN3BpZllHRjk1OEEKQ2VwL2lBWlBFcW5Xc0xLcHMycDBqOEpGSEg1eXovYXd1bkRwRDhNb0d1NUM0cTdLSHJoeEpDYlc0bUw3OVVWQgpCbWwxTUpQZTM5a3AwSFVlRlRVVUhYdU02TmRKZ3lVRmtZTE9ES3IxaFF3dStFdzNzMUJlSmpLdkRpZm1xdGJyCnVKY1l1MEZjNHNWeEhKQXl2bTQ5elZqWFN4VGkvMUl1eHdveUp5KzhRbmY5bDdpTWkyK0JpRXJLKzNYUnlZOUwKTWcxNEQ4RUNnWUVBKzkxdm05V0ZhN1Jxek10VU5KQUZqRGwxcW83d0lDaHhJU2ZMdUVxRVgwUng3b3gyYlRyagp4VlJaNnRIdkd0S0NibHVZa1BhL00ySGhqT2JKeVRZYjBGcUx5bkZKVDFQekZPcVVJSFpVcUg4cEVWRXkyRExtCnFTeDFqM1pBd1cxUWQvaUtvakMyR2hEd0syYTJZZ2Fxb1JiL0tzQlN5N3JnL21oZ2IwTlpEck1DZ1lFQTNYdlIKcUROWDMvK0VpOWR1V3U1RGlNWVEzZTNnVnl5RGJuT1J2Y3BJZ2x2TDlVcFZiVVcvVWdpT1VEQTBYSzN3M0o0agovTHRsT0xvZnp2c1NsYTJjZWptRVkxYkFsL3hSVkpyWWJaWlRjYlhmUXlrMWsxUzEyREVlbElSd3dXc0RXbGQ5CmsrZmRqd09sWGVCUHJWeWVCK1BmRCsvb2pVc1d5Mk5EeUROckdqMENnWUVBNnkrYVFZei8ybFFOaXBDdlg2bkEKMUhEdlZFWEhLbkE1TzNtYXZNc3drbmtxWGxQaFhod29ocUkrbUl4U1Z0eU5tUm1FL0pDOGQvR0ZtWG9Fb1JRYQpvdE42UjU3RGt3VFVMd3JoS1BMMkdLVXRKeE9JZytQOENhc1BWOWhYbllkREpkUDdPSHArQVJjaC9aVWE1NnhMCjlzS3ZvUzhYNFUvdk93RWlVNk15N1FzQ2dZQWxsa2ZFVmNKSi8yRU5JbWhXQWkxdjNyMHFESjZQN0x2NVdKK1oKSitVYVNsM1lxTjdLaHBXclpFeFNpM3UzWnNXRGkwcnNMeGxFZ1VHNHJKOUF5NC9NcGtveldadWhyMjVWLzFsUApiNzJGaEtuNUNkdFB2NGFFeEFFK2p5TmJqNytuNjBVaWZxejVBbE5rRlJjd2dwRkhJWUxQZjVWbHRTS1BMYTlwCklHREN1UUtCZ1FDTGJJWEI3aHc2dGhHTitNVGNwK0Q1dXhacGYzcTB1eTc5Q3IxMktuM2ltZVI0c1Nmd2Q3RHgKSDdGeStMV2tQbHU2elNYamNIWFVRMDgwb1BoREVKYlZvN0I1WkJKWFhqeDRoWE1oVGdCaE5rY0tHL1dsdCtjeQpKSkdmTlY5dzIvVG5ZWW9pbFgxT1BTdk4rejNLN1AvRmMyUWVZS3c0c090aWsyOWhJTWJZTkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
description = "Private key used for webhook signatures. You should generate one using this command `openssl genrsa 2048 | base64`."

[[variables]]
key = "LAGO_API_SECRET_KEY_BASE"
label = "API | Secret Key"
generate = true
description = "Secret key used for session encryption. You can generate one using command `openssl rand -hex 64`."

[[variables]]
key = "LAGO_API_SENTRY_DSN"
label = "API | Sentry DSN"
description = "Sentry DSN key for error and performance tracking."

[[variables]]
key = "LAGO_API_SIDEKIQ_WEB"
label = "API | Sidekiq Web"
description = "Activate the Sidekiq web UI, disabled by default."

[[variables]]
key = "LAGO_API_USE_AWS_S3"
label = "API | Use AWS S3"
default = "false"
description = "Whether to use AWS S3 for file storage."

[[variables]]
key = "LAGO_DISABLE_SIGNUP"
label = "Application | Disable Sign-Up"
default = "false"
description = "Whether to disable registration."

[[variables]]
key = "LAGO_ENVIRONMENT"
label = "General | Environment"
default = "production"
description = "Environment of the application. Should be left untouched."

[[variables]]
key = "LAGO_VERSION"
label = "General | Lago Version"
default = "v0.11.0-alpha"
description = "Check out their valid tags at https://hub.docker.com/r/getlago/api/tags"

[[variables]]
key = "POSTGRES_DB"
label = "Database | Name"
default = "lago"
description = "Name of the PostgreSQL."

[[variables]]
key = "POSTGRES_PASSWORD"
label = "Database | User Password"
generate = true
description = "Password of the PostgreSQL user."

[[variables]]
key = "POSTGRES_PGDATA"
label = "Database | Data Directory"
default = "/data/postgres"
description = "Path to the data directory within PostgreSQL."

[[variables]]
key = "POSTGRES_USER"
label = "Database | User Name"
default = "lago"
description = "Name of the PostgreSQL user."

[[variables]]
key = "POSTGRES_VERSION"
label = "General | PostgreSQL Version"
default = "14.0-alpine"
description = "Check out their valid tags at https://hub.docker.com/_/postgres/tags"

[[variables]]
key = "REDIS_VERSION"
label = "General | Redis Version"
default = "6.2-alpine"
description = "Check out their valid tags at https://hub.docker.com/_/redis/tags"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."
