slug = "litestream"
name = "Litestream"
category = "Database"
description = "Streaming replication for SQLite"
keywords = ["litestream"]
compose = '''
services:
  litestream:
    volumes:
    - litestream-data:/data
    - litestream-config:/config
    environment:
      LITESTREAM_ACCESS_KEY_ID: '{{ACCESS_KEY_ID}}'
      LITESTREAM_SECRET_ACCESS_KEY: '{{SECRET_ACCESS_KEY}}'
volumes:
  litestream-data:
  litestream-config:
'''

[[variables]]
key = "ACCESS_KEY_ID"
label = "Access key ID"
generate = true
description = "Enter your replica-specific authentication key"

[[variables]]
key = "SECRET_ACCESS_KEY"
label = "Secret access key"
generate = true
description = "Enter your replica-specific secret key"
