slug = "matomo"
name = "Matomo analytics"
category = "Analytics"
description = "Matomo tracks online visits to one or more websites and displays reports on these visits for analysis"
keywords = ["analytics", "matomo"]
http_port = 80
compose = '''
services:
  matomo-db:
    image: mariadb:{{MARIADB_VERSION}}
    command: --max-allowed-packet=64MB
    volumes:
    - matomo-db-data:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_DISABLE_UPGRADE_BACKUP: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
      MARIADB_DATABASE: matomo
      MARIADB_USER: matomo
      MARIADB_PASSWORD: '{{DB_PASS}}'
      MARIADB_ROOT_PASSWORD: '{{DB_ROOT_PASS}}'
  matomo:
    depends_on:
    - matomo-db
    image: matomo:{{MATOMO_VERSION}}
    volumes:
    - matomo-data:/var/www/html
    ports:
    - '{{HTTP_PORT}}:80'
    environment:
      MATOMO_DATABASE_HOST: matomo-db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: '{{DB_PASS}}'
      MATOMO_DATABASE_DBNAME: matomo
volumes:
  matomo-db-data:
  matomo-data:
'''

[[variables]]
key = "DB_PASS"
label = "Matomo Database Password"
generate = true
description = "Password for the Matomo MariaDB application user (generated automatically)"

[[variables]]
key = "DB_ROOT_PASS"
label = "MariaDB Root Password"
generate = true
description = "The root password for the MariaDB instance (generated automatically)"

[[variables]]
key = "MARIADB_VERSION"
label = "MariaDB Version"
default = "lts"
description = "MariaDB image tag, see https://hub.docker.com/_/mariadb?tab=tags"

[[variables]]
key = "MATOMO_VERSION"
label = "Matomo Version"
default = "5"
description = "Check out their docker page for the valid tags https://hub.docker.com/_/matomo?tab=tags"
