slug = "metabase"
name = "Metabase"
category = "Monitoring"
description = "Metabase is the easy, open source way for everyone in your company to ask questions and learn from data."
keywords = ["metabase"]
compose = '''
services:
  metabase:
    image: metabase/metabase:{{MB_VERSION}}
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: '{{DB_PASS}}'
      MB_DB_HOST: metabase-db
      MB_EMAIL_SMTP_HOST: '{{SMTP_HOST}}'
      MB_EMAIL_SMTP_PORT: '{{SMTP_PORT}}'
      MB_EMAIL_SMTP_USERNAME: '{{SMTP_USER}}'
      MB_EMAIL_SMTP_PASSWORD: '{{SMTP_PASS}}'
    volumes:
    - metabase-data:/metabase-data
    ports:
    - '{{HTTP_PORT}}:3000'
  metabase-db:
    image: postgres:12-alpine
    volumes:
    - metabase-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: '{{DB_PASS}}'
      POSTGRES_DB: metabase
volumes:
  metabase-data:
  metabase-db:
'''

[[variables]]
key = "DB_PASS"
label = "Database Password"
generate = true

[[variables]]
key = "MB_VERSION"
label = "Metabase Version"
default = "v0.38.0-rc1"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/metabase/metabase/tags"

[[variables]]
key = "SMTP_HOST"
label = "SMTP Host"
description = "OPTIONAL"

[[variables]]
key = "SMTP_PASS"
label = "SMTP Password"
description = "OPTIONAL"

[[variables]]
key = "SMTP_PORT"
label = "SMTP Port"
description = "OPTIONAL"

[[variables]]
key = "SMTP_USER"
label = "SMTP User"
description = "OPTIONAL"
