slug = "monica"
name = "Monica"
category = "App"
description = "Monica is a great open source personal relationship management system to organize the interactions with your loved ones."
keywords = ["monica"]
compose = '''
services:
  monica:
    depends_on:
    - monica-mariadb
    image: monica:{{MONICA_VERSION}}
    restart: always
    environment:
      APP_KEY: '{{GEN_RANDOM_HEX}}(32)'
      DB_HOST: monica-mariadb
      DB_DATABASE: '{{MARIADB}}-db'
      DB_USERNAME: '{{MARIADB}}-user'
      DB_PASSWORD: '{{MARIADB}}-pass'
      APP_ENV: production
    volumes:
    - monica-storage:/var/www/html/storage
  monica-mariadb:
    image: mariadb:{{MARIADB_VERSION}}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: '{{MARIADB}}-db'
      MYSQL_USER: '{{MARIADB}}-user'
      MYSQL_PASSWORD: '{{MARIADB}}-pass'
    volumes:
    - monica-mariadb-data:/var/lib/mysql
    restart: unless-stopped
    ports:
    - '{{HTTP_PORT}}:3306'
volumes:
  monica-storage:
  monica-mariadb-data:
'''

[[variables]]
key = "GEN_RANDOM_HEX"
label = "Gen Random Hex"
default = ""

[[variables]]
key = "MARIADB"
label = "Mariadb"
default = ""

[[variables]]
key = "MARIADB_VERSION"
label = "MariaDB Version"
default = "10.5.6"
description = "Check out their docker page for the valid tags https://hub.docker.com/r/library/mariadb/tags/"

[[variables]]
key = "MONICA_VERSION"
label = "Monica Docker version"
default = "3.7"
description = "Check out this page for the valid tags Find on https://hub.docker.com/_/monica?tab=tags. Use the Apache tag otherwise it won't work."
