slug = "nginx-redirect"
name = "Nginx Redirect"
category = "App"
description = "A simple nginx image preloaded with redirect config that lets you redirect all incoming requests to another URL. Useful for creating domain aliases."
keywords = ["nginx", "redirect"]
http_port = 80
compose = '''
services:
  nginx-redirect:
    image: caprover/nginx-redirect:1-14d89df
    ports:
      - '{{HTTP_PORT}}:80'
    environment:
      RETURN_LOCATION: return 301 {{REDIRECT_URL}}$$request_uri;
'''

[[variables]]
key = "REDIRECT_URL"
label = "Redirect address"
default = "https://example.com"
description = "The destination URL that all requests are redirected to (e.g. https://example.com)."
