slug = "owncast"
name = "Owncast"
category = "Communication"
description = "Self-hosted live video and web chat server"
keywords = ["owncast"]
http_port = 8080
compose = '''
services:
  owncast:
    image: gabekangas/owncast:{{OWNCAST_VERSION}}
    ports:
    - '{{HTTP_PORT}}:8080'
    - '{{OWNCAST_RMTP_PORT}}:1935'
    volumes:
    - owncast:/app/data
volumes:
  owncast:
'''

[[variables]]
key = "OWNCAST_RMTP_PORT"
label = "Networking | RMTP Port"
default = "1935"
description = "Port of the RMTP service. Should not be changed."

[[variables]]
key = "OWNCAST_VERSION"
label = "General | Version Tag"
default = "0.0.12"
description = "Check out their valid tags at https://hub.docker.com/r/gabekangas/owncast/tags"
