slug = "posthog"
name = "PostHog"
category = "Analytics"
description = "🦔 PostHog provides open-source product analytics, session recording, feature flagging and A/B testing that you can self-host."
keywords = ["posthog"]
http_port = 8000
compose = '''
services:
  posthog-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: '{{POSTGRES_USER}}'
      POSTGRES_DB: '{{POSTGRES_DB}}'
      POSTGRES_PASSWORD: '{{POSTGRES_PASSWORD}}'
    volumes:
    - posthog-postgres-data:/var/lib/postgresql/data
  posthog-redis:
    image: redis:6.2.7-alpine
    command: sh -c "redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb"
  posthog-redis7:
    image: redis:7.2-alpine
    command: sh -c "redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb"
  posthog-zookeeper:
    image: zookeeper:3.7.0
    volumes:
    - posthog-zookeeper-datalog:/datalog
    - posthog-zookeeper-data:/data
    - posthog-zookeeper-logs:/logs
  posthog-clickhouse:
    image: clickhouse/clickhouse-server:23.6.1.1524
    depends_on:
    - posthog-kafka
    - posthog-zookeeper
    volumes:
    - clickhouse-data:/var/lib/clickhouse
  posthog-kafka:
    image: bitnami/kafka:2.8.1
    environment:
      KAFKA_BROKER_ID: 1001
      KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://posthog-kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: posthog-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'true'
    depends_on:
    - posthog-zookeeper
    volumes:
    - posthog-kafka-data:/bitnami/kafka
  posthog-worker:
    image: posthog/posthog:{{POSTHOG_VERSION}}
    command: ./bin/docker-worker-celery --with-scheduler
    environment:
      SITE_URL: '{{APP_URL}}'
      SECRET_KEY: '{{SECRET_KEY}}'
      DATABASE_URL: postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@posthog-db:{{POSTGRES_PORT}}/{{POSTGRES_DB}}
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      KAFKA_HOSTS: posthog-kafka:9092
      IS_BEHIND_PROXY: '{{BEHIND_PROXY}}'
      TRUST_ALL_PROXIES: '{{TRUST_ALL_PROXIES}}'
      CLICKHOUSE_SECURE: '{{CLICKHOUSE_SECURE}}'
      DISABLE_SECURE_SSL_REDIRECT: '{{DISABLE_SSL_REDIRECT}}'
      OBJECT_STORAGE_ACCESS_KEY_ID: '{{OBJECT_STORAGE_ROOT_USER}}'
      OBJECT_STORAGE_SECRET_ACCESS_KEY: '{{OBJECT_STORAGE_ROOT_PASSWORD}}'
      OBJECT_STORAGE_ENDPOINT: http://posthog-objectstorage:19000
      OBJECT_STORAGE_ENABLED: '{{ENABLE_OBJECT_STORAGE}}'
  posthog-objectstorage:
    image: minio/minio:RELEASE.2022-06-25T15-50-16Z
    volumes:
    - posthog-objectstorage:/data
    environment:
      MINIO_ROOT_USER: '{{OBJECT_STORAGE_ROOT_USER}}'
      MINIO_ROOT_PASSWORD: '{{OBJECT_STORAGE_ROOT_PASSWORD}}'
    command: sh -c 'mkdir -p /data/posthog && minio server --address ":19000" --console-address ":19001" /data'
  posthog-plugin:
    image: posthog/posthog:{{POSTHOG_VERSION}}
    depends_on:
    - posthog-db
    - posthog-redis
    - posthog-clickhouse
    - posthog-kafka
    - posthog-objectstorage
    environment:
      SECRET_KEY: '{{SECRET_KEY}}'
      SITE_URL: '{{APP_URL}}'
      DATABASE_URL: postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@posthog-db:{{POSTGRES_PORT}}/{{POSTGRES_DB}}
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      KAFKA_HOSTS: posthog-kafka:9092
      DISABLE_SECURE_SSL_REDIRECT: '{{DISABLE_SSL_REDIRECT}}'
      OBJECT_STORAGE_ACCESS_KEY_ID: '{{OBJECT_STORAGE_ROOT_USER}}'
      OBJECT_STORAGE_SECRET_ACCESS_KEY: '{{OBJECT_STORAGE_ROOT_PASSWORD}}'
      OBJECT_STORAGE_ENDPOINT: http://posthog-objectstorage:19000
      OBJECT_STORAGE_ENABLED: '{{ENABLE_OBJECT_STORAGE}}'
      CLICKHOUSE_SECURE: '{{CLICKHOUSE_SECURE}}'
      CDP_REDIS_HOST: posthog-redis7
      CDP_REDIS_PORT: 6379
    command: ./bin/plugin-server
  posthog-web:
    image: posthog/posthog:{{POSTHOG_VERSION}}
    depends_on:
    - posthog-db
    - posthog-redis
    - posthog-clickhouse
    - posthog-kafka
    environment:
      SITE_URL: '{{APP_URL}}'
      SECRET_KEY: '{{SECRET_KEY}}'
      DATABASE_URL: postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@posthog-db:{{POSTGRES_PORT}}/{{POSTGRES_DB}}
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      KAFKA_HOSTS: posthog-kafka:9092
      IS_BEHIND_PROXY: '{{BEHIND_PROXY}}'
      TRUST_ALL_PROXIES: '{{TRUST_ALL_PROXIES}}'
      CLICKHOUSE_SECURE: '{{CLICKHOUSE_SECURE}}'
      DISABLE_SECURE_SSL_REDIRECT: '{{DISABLE_SSL_REDIRECT}}'
      OBJECT_STORAGE_ACCESS_KEY_ID: '{{OBJECT_STORAGE_ROOT_USER}}'
      OBJECT_STORAGE_SECRET_ACCESS_KEY: '{{OBJECT_STORAGE_ROOT_PASSWORD}}'
      OBJECT_STORAGE_ENDPOINT: http://posthog-objectstorage:19000
      OBJECT_STORAGE_ENABLED: '{{ENABLE_OBJECT_STORAGE}}'
    command: sh -c "./bin/migrate && ./bin/docker-server"
    ports:
    - '{{HTTP_PORT}}:8000'
  posthog-elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      cluster.routing.allocation.disk.threshold_enabled: true
      cluster.routing.allocation.disk.watermark.low: 512mb
      cluster.routing.allocation.disk.watermark.high: 256mb
      cluster.routing.allocation.disk.watermark.flood_stage: 128mb
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      xpack.security.enabled: false
    expose:
    - 9200
    volumes:
    - posthog-elasticsearch:/var/lib/elasticsearch/data
  posthog-temporal:
    image: temporalio/auto-setup:1.20.0
    environment:
      DB: postgresql
      DB_PORT: '{{POSTGRES_PORT}}'
      POSTGRES_USER: '{{POSTGRES_USER}}'
      POSTGRES_PWD: '{{POSTGRES_PASSWORD}}'
      POSTGRES_SEEDS: posthog-db
      ENABLE_ES: '{{ENABLE_ELASTIC_SEARCH}}'
      ES_SEEDS: posthog-elasticsearch
      ES_VERSION: v7
    depends_on:
      posthog-db:
        condition: service_healthy
      posthog-elasticsearch:
        condition: service_started
  posthog-temporal-admin-tools:
    image: temporalio/admin-tools:1.20.0
    environment:
      TEMPORAL_CLI_ADDRESS: posthog-temporal:7233
    depends_on:
    - posthog-temporal
  posthog-temporal-ui:
    image: temporalio/ui:2.10.3
    environment:
      TEMPORAL_ADDRESS: posthog-temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    depends_on:
    - posthog-temporal
    - posthog-db
  posthog-temporal-django-worker:
    image: posthog/posthog:{{POSTHOG_VERSION}}
    command: ./bin/temporal-django-worker
    environment:
      SITE_URL: '{{APP_URL}}'
      SECRET_KEY: '{{SECRET_KEY}}'
      DATABASE_URL: postgres://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@posthog-db:{{POSTGRES_PORT}}/{{POSTGRES_DB}}
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      KAFKA_HOSTS: posthog-kafka:9092
      IS_BEHIND_PROXY: '{{BEHIND_PROXY}}'
      TRUST_ALL_PROXIES: '{{TRUST_ALL_PROXIES}}'
      CLICKHOUSE_SECURE: '{{CLICKHOUSE_SECURE}}'
      DISABLE_SECURE_SSL_REDIRECT: '{{DISABLE_SSL_REDIRECT}}'
      TEMPORAL_HOST: posthog-temporal
    depends_on:
    - posthog-db
    - posthog-redis
    - posthog-clickhouse
    - posthog-kafka
    - posthog-objectstorage
    - posthog-temporal
volumes:
  posthog-postgres-data:
  posthog-zookeeper-datalog:
  posthog-zookeeper-data:
  posthog-zookeeper-logs:
  clickhouse-data:
  posthog-kafka-data:
  posthog-objectstorage:
  posthog-elasticsearch:
'''

[[variables]]
key = "BEHIND_PROXY"
label = "Is PostHog running behind a proxy"
default = "true"
description = "Set to true if PostHog is running behind proxy (Caddy, nginx)"

[[variables]]
key = "CLICKHOUSE_SECURE"
label = "Clickhouse secure"
default = "false"
description = "Whether to secure ClickHouse connection"

[[variables]]
key = "DISABLE_SSL_REDIRECT"
label = "Disable Secure SSL Redirect"
default = "true"
description = "Disables automatic redirect from port 80 (HTTP) to port 443 (HTTPS)."

[[variables]]
key = "ENABLE_ELASTIC_SEARCH"
label = "Enable Elastic Search"
default = "false"
description = "Enable elastic search with Temporal"

[[variables]]
key = "ENABLE_OBJECT_STORAGE"
label = "Enable Object storage"
default = "true"

[[variables]]
key = "APP_URL"
label = "Public URL"
default = ""
description = "Public base URL PostHog uses to build links (e.g. https://posthog.example.com). Set after the domain is assigned; leave blank to use the request host."

[[variables]]
key = "OBJECT_STORAGE_ROOT_PASSWORD"
label = "Object Storage Password Key"
generate = true
description = "The secret key for the root user"

[[variables]]
key = "OBJECT_STORAGE_ROOT_USER"
label = "Object Storage Root User"
default = "object_storage_root_user"
description = "The access key for the root user for MinIO"

[[variables]]
key = "POSTGRES_DB"
label = "Postgres DB name"
default = "posthog"

[[variables]]
key = "POSTGRES_PASSWORD"
label = "Postgres Password"
generate = true

[[variables]]
key = "POSTGRES_PORT"
label = "Postgres Port"
default = "5432"

[[variables]]
key = "POSTGRES_USER"
label = "Postgres User"
default = "posthog"

[[variables]]
key = "POSTHOG_VERSION"
label = "PostHog's version"
default = "e2f4b4a8b46667f75ad9bdacf4a487a5dd2d5dbf"

[[variables]]
key = "SECRET_KEY"
label = "PostHog Secret Key"
generate = true

[[variables]]
key = "TRUST_ALL_PROXIES"
label = "Trust all proxies"
default = "false"
description = "Determines if all proxies can be trusted."
