slug = "qbittorrent"
name = "qBittorrent"
category = "App"
description = "qBittorrent BitTorrent client"
keywords = ["qbittorrent"]
http_port = 8080
compose = '''
services:
  qbittorrent:
    image: linuxserver/qbittorrent:{{QBITTORRENT_VERSION}}
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{TZ}}'
      UMASK: '022'
      WEBUI_PORT: '8080'
    ports:
    - '{{HTTP_PORT}}:8080'
    - '6881:6881'
    - '6881:6881/udp'
    volumes:
    - qbittorrent-config:/config
    - '{{PATH_TO_DOWNLOADS}}:/downloads'
volumes:
  qbittorrent-config:
'''

[[variables]]
key = "PATH_TO_DOWNLOADS"
label = "Path to downloads folder"
default = "qbittorrent-downloads"
description = "Path to downloads folder where you want to save the downloaded torrents. You can mention an existing directory here too. Eg. /home/user/downloads/"

[[variables]]
key = "QBITTORRENT_VERSION"
label = "qBittorrent Version"
default = "latest"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/linuxserver/qbittorrent/tags"

[[variables]]
key = "TZ"
label = "Time Zone"
default = "Europe/Brussels"
description = "Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
