slug = "readarr"
name = "Readarr"
category = "App"
description = "Readarr - An ebook collection manager for Usenet and BitTorrent users."
keywords = ["readarr"]
compose = '''
services:
  readarr:
    image: lscr.io/linuxserver/readarr:{{READARR_VERSION}}
    environment:
      TZ: '{{TZ}}'
      PUID: '{{PUID}}'
      PGID: '{{GUID}}'
    volumes:
    - readarr-data:/config
    - readarr-books:/books
    - readarr-downloads:/downloads
    ports:
    - '{{HTTP_PORT}}:8787'
volumes:
  readarr-data:
  readarr-books:
  readarr-downloads:
'''

[[variables]]
key = "GUID"
label = "Group ID"
default = "1000"
description = "Group ID for the process, run (id $user) in your instance to see the id"

[[variables]]
key = "PUID"
label = "User ID"
default = "1000"
description = "User ID for the process, run (id $user) in your instance to see the id"

[[variables]]
key = "READARR_VERSION"
label = "Overseerr Version"
default = "0.3.12-nightly"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/linuxserver/readarr/tags"

[[variables]]
key = "TZ"
label = "Time Zone"
default = "America/Chicago"
description = "Set the timezone. Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
