slug = "rustfs"
name = "RustFS"
category = "Storage"
description = "RustFS is a high-performance distributed object storage software built using Rust"
keywords = ["rustfs"]
compose = '''
services:
  rustfs:
    image: rustfs/rustfs:{{RUSTFS_VERSION}}
    volumes:
    - rustfs-db-data:/data
    restart: always
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_CONSOLE_ENABLE: 'true'
      RUSTFS_EXTERNAL_ADDRESS: https://rustfs-api.{{ROOT_DOMAIN}}
      RUSTFS_ACCESS_KEY: '{{ACCESS_KEY}}'
      RUSTFS_SECRET_KEY: '{{SECRET_KEY}}'
    ports:
    - '{{HTTP_PORT}}:9001'
  rustfs-api:
    image: caprover/nginx-reverse-proxy:1-cc035d1
    restart: always
    depends_on:
    - rustfs
    environment:
      UPSTREAM_HTTP_ADDRESS: http://rustfs:9000
      CLIENT_MAX_BODY_SIZE: '0'
volumes:
  rustfs-db-data:
'''

[[variables]]
key = "ACCESS_KEY"
label = "RustFS User Access Key"
generate = true
description = "Access key for `RUSTFS_ACCESS_KEY`. If unset, RustFS defaults to `rustfsadmin`. RustFS strongly recommends specifying a unique, long, and random value for all environments."

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."

[[variables]]
key = "RUSTFS_VERSION"
label = "RustFS Version"
default = "1.0.0-alpha.77"
description = "Check out their Docker page for the valid tags https://hub.docker.com/r/rustfs/rustfs/tags"

[[variables]]
key = "SECRET_KEY"
label = "RustFS Secret Key"
generate = true
description = "Secret key for `RUSTFS_SECRET_KEY`. If unset, RustFS defaults to `rustfsadmin`. RustFS strongly recommends specifying a unique, long, and random value for all environments."
