slug = "surrealdb"
name = "SurrealDB"
category = "Database"
description = "SurrealDB is an innovative NewSQL cloud database, suitable for serverless applications, jamstack applications, single-page applications, and traditional applications."
keywords = ["surrealdb"]
compose = '''
services:
  surrealdb-db:
    volumes:
    - surrealdb-db-data:/data
    restart: always
    environment:
      USER: '{{DB_USER}}'
      PASS: '{{DB_PASS}}'
volumes:
  surrealdb-db-data:
'''

[[variables]]
key = "DB_PASS"
label = "SurrealDB root password"

[[variables]]
key = "DB_USER"
label = "SurrealDB root user"
