slug = "tiddlywiki"
name = "TiddlyWiki"
category = "CMS"
description = "TiddlyWiki is a personal wiki and a non-linear notebook for organising and sharing complex information"
keywords = ["tiddlywiki"]
compose = '''
services:
  tiddlywiki:
    image: nicolaw/tiddlywiki
    restart: always
    volumes:
    - tiddlywiki-data:/var/lib/tiddlywiki
    environment:
      TW_USERNAME: '{{WIKUSERNAME}}'
      TW_PASSWORD: '{{WIKIPASSWORD}}'
      NODE_MEM: '{{NODEMEM}}'
    ports:
    - '{{HTTP_PORT}}:8080'
volumes:
  tiddlywiki-data:
'''

[[variables]]
key = "NODEMEM"
label = "Max Memory"
default = "400"
description = "Limit the memory that the server can consume"

[[variables]]
key = "WIKIPASSWORD"
label = "Password"
description = "Password for authentication (leave blank for a public wiki)"

[[variables]]
key = "WIKUSERNAME"
label = "Username"
default = "anonymous"
description = "Username for authentication (leave blank for a public wiki)"
