slug = "weblate"
name = "weblate"
category = "App"
description = "Weblate is a copylefted libre software web-based continuous localization system, used by over 1150 libre projects and companies in more than 115 countries."
keywords = ["weblate"]
compose = '''
services:
  weblate-redis:
    image: redis:{{REDIS_VERSION}}
    volumes:
    - weblate-cache-data:/app/data
  weblate-postgres:
    image: postgres:{{POSTGRES_VERSION}}
    volumes:
    - weblate-postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: '{{PG_PASS}}'
      POSTGRES_DB: weblate
  weblate:
    image: weblate/weblate:{{WEBLATE_VERSION}}
    depends_on:
    - weblate-postgres
    - weblate-redis
    volumes:
    - weblate-data:/app/data
    restart: always
    environment:
      WEBLATE_DEBUG: 0
      WEBLATE_LOGLEVEL: INFO
      WEBLATE_ADMIN_EMAIL: '{{ADMIN_EMAIL}}'
      WEBLATE_ADMIN_PASSWORD: '{{ADMIN_PASSWORD}}'
      WEBLATE_SERVER_EMAIL: '{{SERVER_EMAIL}}'
      WEBLATE_DEFAULT_FROM_EMAIL: '{{EMAIL_FROM}}'
      WEBLATE_REGISTRATION_OPEN: '{{OPEN_REGISTRATION}}'
      POSTGRES_PASSWORD: '{{PG_PASS}}'
      POSTGRES_USER: weblate
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: weblate-postgres
      REDIS_HOST: weblate-redis
      WEBLATE_SITE_DOMAIN: weblate.{{ROOT_DOMAIN}}
      WEBLATE_SITE_TITLE: weblate Weblate
      WEBLATE_ADMIN_NAME: Weblate Admin
      POSTGRES_PORT: 5432
      REDIS_PORT: 6379
    ports:
    - '{{HTTP_PORT}}:8080'
volumes:
  weblate-cache-data:
  weblate-postgres-data:
  weblate-data:
'''

[[variables]]
key = "ADMIN_EMAIL"
label = "Email of the first user and administrator of weblate"
description = "Will be used to login to weblate"

[[variables]]
key = "ADMIN_PASSWORD"
label = "Password of the first user and administrator of weblate"
description = "Will be used to login to weblate"

[[variables]]
key = "EMAIL_FROM"
label = "Weblate FROM email"
description = "(eg weblate@example.com)"

[[variables]]
key = "OPEN_REGISTRATION"
label = "Allow open registration of people (0/1)"
default = "0"
description = "Do you allow people to register openly to the platform?"

[[variables]]
key = "PG_PASS"
label = "Postgres Password"
description = "Password must be at least 30 characters.  Please use a random string."

[[variables]]
key = "POSTGRES_VERSION"
label = "Postgres Docker version"
default = "14-alpine"
description = "Check out their Docker page for the valid versions https://hub.docker.com/r/library/postgres/tags"

[[variables]]
key = "REDIS_VERSION"
label = "Redis Docker version"
default = "7-alpine"
description = "Check out their Docker page for the valid versions https://hub.docker.com/r/library/redis/tags"

[[variables]]
key = "ROOT_DOMAIN"
label = "Public domain"
default = ""
description = "Domain used to build public URLs (set your project domain)."

[[variables]]
key = "SERVER_EMAIL"
label = "Weblate server email"
description = "(eg weblate@example.com)"

[[variables]]
key = "WEBLATE_VERSION"
label = "weblate Docker Image tag"
default = "4.14.1-1"
description = "latest, edge, bleeding, or version - Check out their Docker page for the valid tags https://hub.docker.com/r/weblate/weblate/tags"
